### ISSUE TITLE
Spelly is not a function

### ISSUE THREAD

**Issue by SrushtiBhoyar** [dscape/spell#6]
TypeError: Spelly is not a function
    at Object.<anonymous> (work\try3.js:13:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by benolot** [comment]
Try using spell()
